from . import Quron
from . import namozvaqti
from . import namoz_uqilsihi
from . import poklanish
from . import Alloh_ismlar
from . import sura_va_duolar
from . import kichik_buttonlar
from . import qirq_farz
from . import haj
from . import iymon
from . import zakot
from . import ruza